name: Fun App
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.27.2
  flutter_screenutil: ^5.9.1
  image_picker: ^1.1.1
  firebase_storage: ^11.6.11
  cloud_firestore: ^4.15.10

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

