name: project_akhir
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get_cli: ^1.8.1
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_core: ^2.27.2
  flutter_screenutil: ^5.9.1
  image_picker: ^1.1.1
  firebase_storage: ^11.6.11
  cloud_firestore: ^4.15.10
  firebase_auth: ^4.20.0
  intl: ^0.19.0
  pdf: ^3.10.8
  printing: ^5.12.0
  image: ^4.2.0
  audioplayers: ^6.0.0

dev_dependencies: 
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter
  

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/Logo_Funtime.jpg"

flutter: 
  assets: 
    - assets/images/
    - assets/sounds/

  fonts: 
    - family: Pattaya
      fonts: 
        - asset: assets/fonts/Pattaya-Regular.ttf
  uses-material-design: true

