// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcM3Px6UM-8j3NgUMMzILKrmoGDhdg71o',
    appId: '1:99415410470:web:d0392d0c24881d1c7423e7',
    messagingSenderId: '99415410470',
    projectId: 'funtimeapp-c839f',
    authDomain: 'funtimeapp-c839f.firebaseapp.com',
    storageBucket: 'funtimeapp-c839f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2Fvec2lMq_dtWOZCdhou4eby0vBfUsZo',
    appId: '1:99415410470:android:c4b3619641914e3c7423e7',
    messagingSenderId: '99415410470',
    projectId: 'funtimeapp-c839f',
    storageBucket: 'funtimeapp-c839f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARwSr7iOuQSbdWGLdc1cT73Yvdf2vLaGU',
    appId: '1:99415410470:ios:424f89dc707f9f297423e7',
    messagingSenderId: '99415410470',
    projectId: 'funtimeapp-c839f',
    storageBucket: 'funtimeapp-c839f.appspot.com',
    iosBundleId: 'com.example.projectAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARwSr7iOuQSbdWGLdc1cT73Yvdf2vLaGU',
    appId: '1:99415410470:ios:424f89dc707f9f297423e7',
    messagingSenderId: '99415410470',
    projectId: 'funtimeapp-c839f',
    storageBucket: 'funtimeapp-c839f.appspot.com',
    iosBundleId: 'com.example.projectAkhir',
  );

}