// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmo1Gsr2WkG2OS_QvEtA8EoWvae0z27QI',
    appId: '1:528589416423:web:d22fe0c259111775cfff42',
    messagingSenderId: '528589416423',
    projectId: 'projectakhir-3736f',
    authDomain: 'projectakhir-3736f.firebaseapp.com',
    storageBucket: 'projectakhir-3736f.appspot.com',
    measurementId: 'G-Y8318GNZP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYB7IDEM5FL_AYWNMcJjibpV4rwVfmwl0',
    appId: '1:528589416423:android:1d86f906558f6caccfff42',
    messagingSenderId: '528589416423',
    projectId: 'projectakhir-3736f',
    storageBucket: 'projectakhir-3736f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmpxeIK4zIxyu95emYJ1NvlIKCE-eJOrw',
    appId: '1:528589416423:ios:4ec438e864828a63cfff42',
    messagingSenderId: '528589416423',
    projectId: 'projectakhir-3736f',
    storageBucket: 'projectakhir-3736f.appspot.com',
    iosBundleId: 'com.example.projectAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmpxeIK4zIxyu95emYJ1NvlIKCE-eJOrw',
    appId: '1:528589416423:ios:4ec438e864828a63cfff42',
    messagingSenderId: '528589416423',
    projectId: 'projectakhir-3736f',
    storageBucket: 'projectakhir-3736f.appspot.com',
    iosBundleId: 'com.example.projectAkhir',
  );
}
